services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres_container
    environment:
      POSTGRES_USER: vasiliy
      POSTGRES_PASSWORD: moskalev
      POSTGRES_DB: moskalev_dev
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

  pgadmin:
    container_name: pgadmin
    restart: always
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dev.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"