### Переменные окружения
@host = http://localhost:8090
@baseUrl = {{host}}/v1/hotel

### Переменные для тестов
@adminLogin = testLogin
@adminPass = qwertyui
@clientLogin = clientTestLogin
@clientPass = qwertyui

### 1. Создание отеля (POST)
POST {{baseUrl}}
Content-Type: application/json
Accept: application/json
Authorization: Basic {{adminLogin}} {{adminPass}}

{
  "name": "Grand Hotel",
  "description": "Luxury hotel in the city center with a great view",
  "title": "The Grand Experience",
  "city": "Moscow",
  "address": "Tverskaya street, 1",
  "distance": 1500
}

> {%
    // Автоматически сохраняем ID созданного отеля в глобальную переменную
    client.global.set("hotelId", response.body.id);
    client.log("Отель успешно создан. Присвоен ID: " + response.body.id);

    // Опциональная проверка статуса
    client.test("Создание отеля прошло успешно", function() {
        client.assert(response.status === 201, "Ожидался статус 201, получен " + response.status);
    });
%}


### 2. Получение всех отелей с пагинацией и сортировкой (GET)
GET {{baseUrl}}?page=0&size=10&sortBy=id&direction=asc
Accept: application/json
Authorization: Basic {{adminLogin}} {{adminPass}}


### 2.1 Получение всех отелей с с фильтрацией через POST  (с пагинацией и сортировкой)
POST {{baseUrl}}/filter?page=0&size=10&sortBy=id&direction=asc
Content-Type: application/json
Accept: application/json
Authorization: Basic {{adminLogin}} {{adminPass}}

{
  "city": "Moscow",
  "nameContains": "Grand",
  "minDistance": 500,
  "maxDistance": 5000,
  "minRating": 4.0
}

### 2.2. Фильтрация только по городу
POST {{baseUrl}}/filter?page=0&size=10&sortBy=id&direction=asc
Content-Type: application/json
Accept: application/json
Authorization: Basic {{adminLogin}} {{adminPass}}

{
  "city": "Moscow"
}

### 2.3. Фильтрация по части названия (case-insensitive)
POST {{baseUrl}}/filter?page=0&size=10&sortBy=name&direction=asc
Content-Type: application/json
Accept: application/json
Authorization: Basic {{adminLogin}} {{adminPass}}

{
  "nameContains": "hotel"
}

### 2.4. Фильтрация по диапазону расстояний
POST {{baseUrl}}/filter?page=0&size=10&sortBy=distance&direction=asc
Content-Type: application/json
Accept: application/json
Authorization: Basic {{adminLogin}} {{adminPass}}

{
  "minDistance": 500,
  "maxDistance": 2000
}

### 2.5. Фильтрация по минимальному рейтингу
POST {{baseUrl}}/filter?page=0&size=10&sortBy=rating&direction=desc
Content-Type: application/json
Accept: application/json
Authorization: Basic {{adminLogin}} {{adminPass}}

{
  "minRating": 3.0
}

### 2.6. Комбинированная фильтрация (все параметры)
POST {{baseUrl}}/filter?page=0&size=5&sortBy=id&direction=asc
Content-Type: application/json
Accept: application/json
Authorization: Basic {{adminLogin}} {{adminPass}}

{
  "city": "Moscow",
  "nameContains": "Grand",
  "minRating": 3.0
}

### 2.7. Пустой фильтр (вернуть все отели)
POST {{baseUrl}}/filter?page=0&size=10&sortBy=id&direction=asc
Content-Type: application/json
Accept: application/json
Authorization: Basic {{adminLogin}} {{adminPass}}

{}

### 2.8. Фильтрация без тела запроса
POST {{baseUrl}}/filter?page=0&size=10&sortBy=id&direction=asc
Accept: application/json
Authorization: Basic {{adminLogin}} {{adminPass}}


### 3. Получение отеля по ID (GET)
### ======================================================================
# Переменная {{hotelId}} подставится автоматически из шага 1,
# либо вы можете заменить её на конкретное число (например, 1)
GET {{baseUrl}}/{{hotelId}}
Accept: application/json
Authorization: Basic {{adminLogin}} {{adminPass}}

### 4. Обновление отеля (PUT)
PUT {{baseUrl}}/{{hotelId}}
Content-Type: application/json
Accept: application/json
Authorization: Basic {{adminLogin}} {{adminPass}}

{
  "name": "Updated Grand Hotel",
  "description": "New description after renovation",
  "title": "Premium Grand Experience",
  "city": "Saint Petersburg",
  "address": "Nevsky prospect, 28",
  "distance": 2500
}

### 5. Удаление отеля (DELETE)
DELETE {{baseUrl}}/{{hotelId}}
Authorization: Basic {{adminLogin}} {{adminPass}}

### 6. Проверка, что отель действительно удален (404)
GET {{baseUrl}}/{{hotelId}}
Accept: application/json
Authorization: Basic {{adminLogin}} {{adminPass}}

